### ISSUE TITLE
Tests for identity

### ISSUE THREAD

**Issue by maurogestoso** [jonsey247/Lowbar#2]
You should test that `identity` returns the same value it's passed. By doing that, you implicitly test that it returns the same type.

e.g.
```javascript
var input = [1, 2, 3];
expect(_.identity(input)).to.equal(input);
```

https://github.com/jonsey247/Lowbar/blob/eb0016ddad7d9bb3d94725fafe129fd0a46968b3/spec/lowbar.spec.js#L19-L32

**Comment by jonsey247** [comment]
Test added and passed
