### ISSUE TITLE
Tests for #first and #last

### ISSUE THREAD

**Issue by maurogestoso** [jonsey247/Lowbar#3]
Second test below is redundant / not testing what it describes:

https://github.com/jonsey247/Lowbar/blob/eb0016ddad7d9bb3d94725fafe129fd0a46968b3/spec/lowbar.spec.js#L50-L58

Test below is redundant.

https://github.com/jonsey247/Lowbar/blob/eb0016ddad7d9bb3d94725fafe129fd0a46968b3/spec/lowbar.spec.js#L65-L68

**Comment by maurogestoso** [comment]
Same applies for #last

**Comment by jonsey247** [comment]
both tests removed as they are not relevant
